version: "3.3"
services:
  api:
    image: node:17-bullseye-slim
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"
      - "5001:5001"
    working_dir: /app
    command: sh -c 
      "npm install -g nest &&
       npm install &&
       npm run build &&
       npm run start:prod
       "
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    entrypoint: "bash -c 'echo -e \"CREATE DATABASE IF NOT EXISTS app_test;\" > /docker-entrypoint-initdb.d/create_app_test_db.sql &&
                          /entrypoint.sh mysqld'"
volumes:
  mysqldata:
    driver: local